services:
  postgresql:
    image: postgres:17
    container_name: api_recettapp-postgresql-1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recettapp
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data:rw
    restart: always