package be.helha.api_recettapp.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an image stored in the system.
 * This class contains metadata and binary data for an image.
 *
 * @author Demba Mohamed Samba
 */

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ImageData {

    /**
     * Unique identifier for the image.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    private String type;

    /**
     * The binary data of the image.
     * Stored as a Large Object (LOB) in the database.
     */
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "imagedata",length = 5242880) // Allow up to 5 MB
    private byte[] imageData;

    /**
     * Represents the recipe associated with this image.
     */
    @ManyToOne
    @JoinColumn(name = "id_recipe", nullable = false)
    private Recipe recipe;

}
