package be.helha.api_recettapp.models;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents an image stored in the system.
 * This class contains metadata and binary data for an image.
 *
 * @author Demba Mohamed Samba
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class ImageData {

    /**
     * Unique identifier for the image.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the image file.
     * This field is mandatory.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The type of the image file (e.g., JPEG, PNG).
     */
    private String type;

    /**
     * The binary data of the image.
     * Stored as a Large Object (LOB) in the database.
     * This field can store up to 5 MB of image data.
     */
    @Lob
    @Basic(fetch = FetchType.LAZY)
    @Column(name = "imagedata", length = 5242880)
    private byte[] imageData;

    /**
     * The recipe associated with this image.
     * This establishes a many-to-one relationship between the image and a recipe.
     */
    @ManyToOne
    @JoinColumn(name = "id_recipe")
    private Recipe recipe;

    /**
     * The evaluation associated with this image.
     * This establishes a many-to-one relationship between the image and an evaluation.
     */
    @ManyToOne
    @JoinColumn(name = "id_evaluation")
    private Evaluation evaluation;
}
