spring:
  application:
    name: api_recettapp
  datasource:
    url: jdbc:postgresql://localhost:5432/recettapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/recettapp
          #URL to validate JWT
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  secret: fjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvxfjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvx
  expirationTokenMs: 3600000
  expirationRefreshTokenMs: 604800000



keycloak:
  auth-server-url: http://localhost:8081/
  realm: recettapp
  resource: backend_recettapp
  credentials:
    secret: v61G34KiyVgiHz9F3mofrr6EWrfOknS3
  public-client: false



paypal:
  client-id : AYNrryhL8K4n1OuZnepGl_L-qo82AYvcKgPNbYrYi7cZKpQsWBDIyxU8_yXlD4PwcxXGR_6zR5CvU2Sq
  client-secret: EELGBaiizFScSj-vA8_AiVQXsjtBHH-rTpQ85cow1zwF0LYcF2jwcXTLKJ3586Krw_HZ0dk2oDJiALut
  api-url: https://api-m.sandbox.paypal.com


