

spring:
  application:
    name: api_recettapp
  datasource:
    url: jdbc:postgresql://localhost:5432/recettapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/recettapp
          #URL to validate JWT
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  secret: fjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvxfjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvx
  expirationTokenMs: 3600000
  expirationRefreshTokenMs: 604800000
