spring:
  application:
    name: api_recettapp
  datasource:
    url: jdbc:postgresql://localhost:5432/recettapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: fjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvxfjkdfngdbjzebnhubvshubsgdvgbjhn435345fsdnbvxhcbghxcbvxcvx
  expirationTokenMs: 3600000
  expirationRefreshTokenMs: 604800000